### ISSUE TITLE
Address scons IndexError in Windows

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/template#50]
On `dev_four` template+gslab_python (and their most recent version to be pulled in `#68-rmgoogledrive`), on Windows, running Scons produce the following: 

```
C:\Users\quanle\template>scons
scons: Reading SConscript files ...
IndexError: list index out of range:

C:\Users\quanle\template>scons --debug=stacktrace
scons: Reading SConscript files ...
IndexError: list index out of range:
```

The last time we got an IndexError with empty stacktrace, we were accidentally passing a None object to one of Scons' deep function (`NoCache` was the offender), so that's where I would start. My suggestion is to comment out lines in the SConstruct until the error stops.

Thanks @lboxell

**Comment by stanfordquan** [comment]
`gslab_python` test result seems promising:

```

======================================================================
FAIL: test_create_size_dictionary (test_size_warning.TestSizeWarning)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python2713\lib\site-packages\mock\mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "C:\Users\quanle\gslab_python\gslab_scons\tests\test_size_warning.py", line 186, in test_create_size_dictionary
    self.assertEqual(len(sizes), 3)
AssertionError: 0 != 3

======================================================================
FAIL: test_is_subpath (test_size_warning.TestSizeWarning)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\quanle\gslab_python\gslab_scons\tests\test_size_warning.py", line 119, in test_is_subpath
    self.assertTrue(sw._is_subpath(**keywords))
AssertionError: False is not true

======================================================================
FAIL: test_list_ignored_files (test_size_warning.TestSizeWarning)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python2713\lib\site-packages\mock\mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "C:\Users\quanle\gslab_python\gslab_scons\tests\test_size_warning.py", line 141, in test_list_ignored_files
    self.assertEqual(len(ignored), len(expect_ignored))
AssertionError: 0 != 3

```

**Comment by stanfordquan** [comment]
Detected the error

```
env = Environment(ENV = {'PATH' : os.environ['PATH']}, 
                  IMPLICIT_COMMAND_DEPENDENCIES = 0,
                  BUILDERS = {'Tablefill':   Builder(action = gs.build_tables),
                              'BuildLyx':    Builder(action = gs.build_lyx),
                              'BuildStata':  Builder(action = gs.build_stata),
                              'BuildPython': Builder(action = gs.build_python)},
                  stata_executable = stata_executable)
```

**Comment by stanfordquan** [comment]
Even

```
env = Environment()
```

returns an error

**Comment by stanfordquan** [comment]
@lboxell I discovered that the `debug` flags setting `sys.tracebackerror = 0`. Removing them fix the issue. I have done so in the above commit, which is on the branch to be pulled in with `gslab_python#68`.

**Comment by stanfordquan** [comment]
@lboxell I committed this to the PR in #48, the bug should be considered fixed.
